# Full Stack open: Continuous integration (part 11)
# by The University of Helsinki
# url : https://courses.mooc.fi/org/uh-cs/courses/full-stack-open-continuous-integration
# created: Sept 22, 2026

# Change Logs :
# 1. Exercise 11.3: 
#    create a new Workflow that outputs "Hello World!" to the console
# 2. Exercise 11.4: 
#    print the date and current directory content in the long format


name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Run command date
        run: |
          date

      - name: Run command ls -l
        run: |
          ls -l
