# Full Stack open: Continuous integration (part 11)
# by The University of Helsinki
# url : https://courses.mooc.fi/org/uh-cs/courses/full-stack-open-continuous-integration
# created: Sept 22, 2026

# Change Logs :
# 1. Exercise 11.5: implement a "Lint" workflow
# 2. Exercise 11.7: add build and test commands
# 3. Exercise 11.9: add simple end-to-end tests
# 4. Exercise 11.11: make deployments automatic to Rander
# 5. Exercise 11.13: add pull request triggers
# 6. Exercise 11.14: run deployment only for main branch
# 7. Exercise 11.15: automatically increase (bump) the version
# 8. Exercise 11.16: not deploy if commit msg contains #skip
# 9. Exercise 11.18: set up Discord notification by using webhook
# 10. Exercise 11.19: splite workflow to logical jobs

name: Deployment pipeline

on:
  push:
    branches:
      - main
      - exercise/11.19
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Run npm test
        run: npm run test

      - name: Run npm build
        run: npm run build

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          if-no-files-found: ignore # Prevents warnings if the folder doesn't exist

  deployment:
    needs: [build_and_test]
    runs-on: ubuntu-latest

    #  github.event_name == 'push' &&

    if: >
      !contains(toJson(github.event.commits.*.message), '#skip')

    steps:
      # simulation failure
      - name: Force failure test
        run: exit 1

      # exercise 11.14: add 'if' to ensure this step is executed only
      # if the code is being merged or push to the main branch
      - run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_and_notification:
    needs: [deployment]
    runs-on: ubuntu-latest
    # exercise 11.14 & 11.16: ensure merge to main AND no #skip keyword

    #  github.event_name == 'push' &&

    if: >
      !contains(toJson(github.event.commits.*.message), '#skip')
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        # exercise 11.15: auto increase (bump) the version
        # use most recent version of github-tag-action as exercise advised
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true # temp remove -> false

      - name: Set short git commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Send Discord Success Notification
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          username: Fullstack Part 11 Hook
          color: 0x0fbf3e
          status: success
          title: "✅ A new version deployed to production"
          description: |
            **Branch:** ${{ github.ref_name }}
            **Commit:**  ${{ steps.vars.outputs.SHORT_SHA }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Job:** ${{ github.job }}

            [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})

  notify_failure:
    needs: [build_and_test, deployment]
    runs-on: ubuntu-latest
    if: >
      always() &&
      (needs.build_and_test.result == 'failure' || 
      needs.deployment.result == 'failure')
    steps:
      - name: Set short git commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Send Discord Failure Notification
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          username: Fullstack Part 11 Hook
          color: 0xfe4c25
          status: failure
          title: "❌ The pipeline encountered an error"
          description: |
            **Branch:** ${{ github.ref_name }}
            **Commit:**  ${{ steps.vars.outputs.SHORT_SHA }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Job:** ${{ github.job }}

            [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
