# Full Stack open: Continuous integration (part 11)
# by The University of Helsinki
# url : https://courses.mooc.fi/org/uh-cs/courses/full-stack-open-continuous-integration
# created: Sept 22, 2026

# Change Logs :
# 1. Exercise 11.5: implement a "Lint" workflow

name: Deployment pipeline

on:
    push:
        branches:
            - main

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Install dependencies
              run: npm install

            - name: Check style
              run: npm run eslint
